*     -INC CCREEL
*
      REAL*8      XZERO,XPI,XGRAND,XPETIT,XZPREC
      REAL*4      XSGRAN,XSPETI,XSZPRE
      COMMON/REEL/XGRAND,XPETIT,XZPREC
      COMMON/REE4/XSGRAN,XSPETI,XSZPRE
      PARAMETER(XZERO=0.D0)
      PARAMETER(XPI=3.141592653589793D0)
*
*             CE COMMON CONTIENT QUELQUES CONSTANTE
*
*                 XZERO=0.
*                 XPI  =3.14159..............
*                 XGRAND= NOMBRE GRAND EN VALEUR ABSOLUE real*8
*                 XPETIT= NOMBRE PETIT EN VALEUR ABSOLUE real*8
*                 xzprec precision machine real*8 relative a 1
*
*                 XSGRAN= NOMBRE GRAND EN VALEUR ABSOLUE real*4
*                 XSPETI= NOMBRE PETIT EN VALEUR ABSOLUE real*4
*                 xszpre precision machine real*4 relative a 1
*
